# Generated by Django 5.2.6 on 2025-09-26 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preço', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nome', models.CharField(max_length=20)),
                ('descricao', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
            },
        ),
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Categoria', models.ManyToManyField(to='cardapio.categoria')),
            ],
            options={
                'verbose_name': 'Cardapio',
                'verbose_name_plural': 'Cardapios',
            },
        ),
        migrations.AddField(
            model_name='categoria',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardapio.item'),
        ),
    ]
