# Generated by Django 5.2.6 on 2025-09-29 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='cardapio.categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mesa',
            name='ocupada',
            field=models.BooleanField(default=False),
        ),
    ]
