# Generated by Django 5.2.6 on 2025-09-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='ocupada',
            field=models.BooleanField(default=False),
        ),
    ]
