# Generated by Django 5.2 on 2025-09-18 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdministradorSistema',
            new_name='Gerente',
        ),
        migrations.AlterModelOptions(
            name='gerente',
            options={'verbose_name': 'Gerente', 'verbose_name_plural': 'Gerentes'},
        ),
    ]
