# Generated by Django 5.2.6 on 2025-09-26 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='Item',
            new_name='item',
        ),
        migrations.RemoveField(
            model_name='comanda',
            name='Pedido',
        ),
        migrations.AddField(
            model_name='comanda',
            name='pedido',
            field=models.ManyToManyField(to='pedido.pedido'),
        ),
    ]
